apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.fastapi.deployment.name }}-app
  labels:
    app: {{ .Values.fastapi.deployment.name }}
spec:
  replicas: {{ .Values.fastapi.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.fastapi.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.fastapi.deployment.name }}
    spec:
      serviceAccountName: {{ .Values.fastapi.deployment.name }}-sa
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}    
      containers:
        - name: {{ .Values.fastapi.deployment.name }}-app
          image: {{ .Values.fastapi.image.repository }}:{{ .Values.fastapi.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: postgres-configmap
            - secretRef:
                name: postgres-secret
          resources:
            {{- toYaml .Values.fastapi.resources | nindent 12 }}
