apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.postgres.statefulsetName }}
spec:
  serviceName: {{ .Values.postgres.serviceName }}
  replicas: {{ .Values.postgres.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.postgres.statefulsetName }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgres.statefulsetName }}
    spec:
      containers:
        - name: postgres
          image: postgres:13
          ports:
            - containerPort: {{ .Values.postgres.port }}
          envFrom:
            - configMapRef:
                name: postgres-configmap
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
            - name: initdb-scripts
              mountPath: /docker-entrypoint-initdb.d/initdb.sql
              subPath: initdb.sql
          resources:
            {{- toYaml .Values.postgres.resources | nindent 12 }}
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: {{ .Values.postgres.statefulsetName }}-pvc
        - name: initdb-scripts
          configMap:
            name: initdb-configmap
  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.postgres.statefulsetName }}-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.postgres.persistence.storage.size }}
