apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap
data:
  POSTGRES_DB: {{ .Values.postgres.database | quote }}
  POSTGRES_USER: {{ .Values.postgres.username | quote }}
  POSTGRES_PORT: "{{ .Values.postgres.port }}"
  POSTGRES_SCHEMA: {{ .Values.postgres.schema | quote }}
  POSTGRES_HOST: {{ printf "%s.%s.svc.cluster.local" .Values.postgres.statefulsetName .Release.Namespace | quote  }}