# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ include "fastapi-bookstore-app.fullname" . }}
#   labels:
#     {{- include "fastapi-bookstore-app.labels" . | nindent 4 }}
# spec:
#   type: {{ .Values.service.type }}
#   ports:
#     - port: {{ .Values.service.port }}
#       targetPort: http
#       protocol: TCP
#       name: http
#   selector:
#     {{- include "fastapi-bookstore-app.selectorLabels" . | nindent 4 }}
